version: 2.1

orbs:
  node: circleci/node@6.1.0

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
  
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
  
  release:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Setup git
          command: git branch --set-upstream-to=origin/release release
      - run:
          name: Authenticate with registry
          command: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Library
          command: npm run build
      - run:
          name: Release
          command: npm run release

workflows:
  test_library:
    jobs:
      - test

  build_library:
    jobs:
      - test
      - build:
          requires:
            - test
  
  release_library:
    jobs:
      - test
      - build:
          requires:
            - test
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - release
