version: 2.1

orbs:
  node: circleci/node@6.1.0

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
  
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
  
  release:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Initialize git user
          command: |
            git config --global user.email "nicolas.aguilar1999@gmail.com"
            git config --global user.name "Nicolas Camacho"
      - run:
          name: Setup git
          command: git branch --set-upstream-to=origin/main main
      - run:
          name: Authenticate with registry
          command: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Library
          command: npm run build
      - run:
          name: Release
          command: npm run release

workflows:
  test_library:
    jobs:
      - test

  build_library:
    jobs:
      - test
      - build:
          requires:
            - test
  
  release_library:
    when:
      condition:
        not:
          equal: [ "<< pipeline.git.base_revision >>", null ]
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: main
            tags:
              only: /^release:/